name: LedgerStream CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'ledger-stream/pom.xml'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
        working-directory: ./ledger-stream

      - name: Build (Tests Planned for Phase 2)
        run: ./mvnw clean compile --no-transfer-progress
        working-directory: ./ledger-stream
